name: "CloudDefense"
description: "Check your Node application for vulnerabilties using CloudDefense"
author: "PG"
branding:
  icon: "alert-triangle"
  color: "yellow"
inputs:
  command:
    description: "Which CloudDefense command to run, defaults to scan"
    default: scan
  project-name:
    description: "Name of the application"
  api-key:
    description: "API key to record the scan"
  path:
    description: "Path to the project"
runs:
  using: "docker"
  image: "docker://cdefense/cdefense:node"
  env:
    SCAN_LANG: node
  args:
  - ${{ inputs.command }}
  - ${{ inputs.project-name }} 
  - ${{ inputs.api-key }} 
  - ${{ inputs.path }} 
